
import mongoose from "mongoose";
import { ENUMS } from "../utils/constants.js";

const attendanceSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  shiftId: { type: mongoose.Schema.Types.ObjectId, ref: "Shift", required: true },
  date: { type: Date, required: true },
  clockIn: { type: Date },
  clockOut: { type: Date },
  totalWorkSeconds: { type: Number, default: 0 },
  totalBreakSeconds: { type: Number, default: 0 },
  islateIn: { type: Boolean, default: false },
  lateInDuration: { type: Number, default: 0 },
  isEarlyOut: { type: Boolean, default: false },
  EarlyOutDuration: { type: Number, default: 0 },
  isOverTime : {type : Boolean ,default : false},
  ExtraTime :{type : Number , default : 0},
  dayStatus: {
    type: Number,
    enum: [
      ENUMS.DAY_STATUS.WORKING,
      ENUMS.DAY_STATUS.WEEKEND,
      ENUMS.DAY_STATUS.FIRSTHALF,
      ENUMS.DAY_STATUS.SECONDHALF,
      ENUMS.DAY_STATUS.HOLIDAY,
    ],
    default: ENUMS.DAY_STATUS.WORKING,
  },
  autoGenerated : {type : Boolean , default :false}

}, { timestamps: true });
attendanceSchema.index({ userId: 1, date: 1 }, { unique: true });

export default mongoose.model("Attendance", attendanceSchema);
